version: '3.9'

services:
  atlas-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <YourStrong@Passw0rd>
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  atals-app:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
        - atlas-db

volumes:
  db_data: